# Follows deployment steps for building a static GCP site here: https://cloud.google.com/community/tutorials/automated-publishing-cloud-build
steps:
  # Install dependencies (yarn install)
  - name: node
    entrypoint: yarn
    args: [ 'install' ]
  # Lint all files (yarn lint-ci)
  - name: node
    entrypoint: yarn
    args: [ 'lint-ci' ]
  # Run all tests (yarn test)
  - name: node
    entrypoint: yarn
    args: [ 'test-ci' ]
  # Create a production build (yarn run build)
  - name: node
    entrypoint: yarn
    args: [ 'run', 'build' ]
  # Update the GCP storage bucket to contain the production build
  # -m processes build artifact files in parallel, -r is recursive,
  # -c avoids re-uploading unchanged files, -d deletes extraneous files in the bucket
  - name: gcr.io/cloud-builders/gsutil
    args: [ "-m", "rsync", "-r", "-c", "-d", "build", "gs://client.djin.dev" ]

